apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
  labels:
    app: ruby-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-app
        image: shyamrkg/rubyappnewusertest1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
